// @ts-check

const { pillars } = require('./docs/publishing/docFlags');

/**
 * Helper: only include a sidebar category if its flag is enabled.
 * Unpublished pillars are completely hidden from the sidebar.
 */
function pillarCategory(flagName, dirName, label, opts = {}) {
  if (!pillars[flagName]) return null;
  return {
    type: 'category',
    label,
    collapsible: opts.collapsible ?? true,
    collapsed: opts.collapsed ?? true,
    items: [{ type: 'autogenerated', dirName }],
    ...(opts.link ? { link: opts.link } : {}),
  };
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guide: [
    // ── Core sections ──
    pillarCategory('introduction', 'introduction', 'Introduction', { collapsed: false }),
    pillarCategory('getting-started', 'getting-started', 'Getting Started', { collapsed: false }),

    // ── Platform Pillars ──
    pillarCategory('elysium-play', 'elysium-play', 'ELYSIUM PLAY'),
    pillarCategory('creation-app', 'creation-app', 'ELYSIUM Creation App'),
    pillarCategory('portal', 'portal', 'ELYSIUM Portal'),
    pillarCategory('geist-engine', 'geist-engine', 'GEIST Engine'),
    pillarCategory('elysium-x', 'elysium-x', 'ELYSIUM X'),
    pillarCategory('wallet', 'wallet', 'ELYSIUM Wallet'),
    pillarCategory('analytics', 'analytics', 'ELYSIUM Analytics'),
    pillarCategory('depin-network', 'depin-network', 'ELYSIUM DePIN Network'),
    pillarCategory('reality-bridge', 'reality-bridge', 'REALITY BRIDGE'),
    pillarCategory('alpha-lab', 'alpha-lab', 'ALPHA Lab', { collapsed: false }),

    // ── Reference & Site sections ──
    pillarCategory('reference', 'reference', 'Reference'),
    pillarCategory('pricing', 'pricing', 'Pricing'),
    pillarCategory('support', 'support', 'Support'),
    pillarCategory('press', 'press', 'Press'),
    pillarCategory('policies', 'policies', 'Policies'),
  ].filter(Boolean),
};

module.exports = sidebars;
