// @ts-check

const { pillars } = require('./docs/publishing/docFlags');

/**
 * Helper: only include a sidebar category if its flag is enabled.
 * Unpublished pillars are completely hidden from the sidebar.
 */
function pillarCategory(flagName, dirName, label, opts = {}) {
  if (!pillars[flagName]) return null;
  return {
    type: 'category',
    label,
    collapsible: opts.collapsible ?? true,
    collapsed: opts.collapsed ?? true,
    items: [{ type: 'autogenerated', dirName }],
    ...(opts.link ? { link: opts.link } : {}),
  };
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guide: [
    // Root-level docs (Introduction, Getting Started)
    {
      type: 'doc',
      id: 'my-home-doc',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },

    // ── Platform Pillars ──
    pillarCategory('elysium-play', 'elysium-play', 'ELYSIUM PLAY'),
    pillarCategory('creation-app', 'creation-app', 'ELYSIUM Creation App'),
    pillarCategory('portal', 'portal', 'ELYSIUM Portal'),
    pillarCategory('geist-engine', 'geist-engine', 'GEIST Engine'),
    pillarCategory('elysium-x', 'elysium-x', 'ELYSIUM X'),
    pillarCategory('wallet', 'wallet', 'ELYSIUM Wallet'),
    pillarCategory('analytics', 'analytics', 'ELYSIUM Analytics'),
    pillarCategory('depin-network', 'depin-network', 'ELYSIUM DePIN Network'),
    pillarCategory('reality-bridge', 'reality-bridge', 'REALITY BRIDGE'),
    pillarCategory('alpha-lab', 'alpha-lab', 'ALPHA Lab', { collapsed: false }),

    // ── Reference ──
    pillarCategory('reference', 'reference', 'Reference'),

    // ── Site sections (always visible) ──
    {
      type: 'autogenerated',
      dirName: 'pricing',
    },
    {
      type: 'category',
      label: 'Support',
      items: [{ type: 'autogenerated', dirName: 'support' }],
    },
    {
      type: 'category',
      label: 'Press',
      items: [{ type: 'autogenerated', dirName: 'press' }],
    },
    {
      type: 'category',
      label: 'Policies',
      items: [{ type: 'autogenerated', dirName: 'policies' }],
    },
  ].filter(Boolean), // Remove null entries from unpublished pillars
};

module.exports = sidebars;
